shop_proj/shop_proj/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("shop_app.urls")),
    path("user/", include("users.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_proj/users/urls.py
from django.contrib import admin
from django.urls import path
from users import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("register", views.register, name="register"),
    path("login", views.user_login, name="login"),
    path("profile", views.user_profile, name="profile"),
    path(
        "logout",
        views.CustomLogoutView.as_view(
            http_method_names=["post", "get", "option"],
        ),
        name="logout",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_proj/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=10)
    email = models.EmailField(max_length=254)
    image = models.ImageField(
        default="user_uploads/default-pfp.jpg",
        upload_to="user_uploads",
        blank=True,
    )

    def __str__(self):
        return self.user.username

shop_proj/users/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            "first_name",
            "last_name",
            "username",
            "email",
            "password",
            "password2",
        ]

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password2 = cleaned_data.get("password2")

        if password != password2:
            raise forms.ValidationError("Passwords do not match.")

        return cleaned_data


class LoginForm(forms.Form):
    username = forms.CharField(label="Username")
    password = forms.CharField(label="Password", widget=forms.PasswordInput)

shop_proj/users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import View
from .forms import *
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


# Create your views here.
def register(request):
    if request.method == "POST":
        user_form = RegistrationForm(
            request.POST or None, request.FILES or None
        )  # Make sure both are included if needed
        if user_form.is_valid():
            user_form.save()
            return redirect("login")
    else:
        user_form = RegistrationForm()

    return render(request, "users/register.html", {"user_form": user_form})


def user_login(request):
    if request.method == "POST":
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            data = login_form.cleaned_data
            user = authenticate(
                request, username=data["username"], password=data["password"]
            )
            if user is not None:
                login(request, user)
                return redirect("home")

    else:
        login_form = LoginForm()
    return render(request, "users/login.html", {"login_form": login_form})


@login_required
def user_profile(request):
    return render(request, "users/profile.html")


class CustomLogoutView(View):
    def get(self, request):
        return render(
            request, "users/logout.html"
        )  # Render the logout confirmation template

    def post(self, request):
        logout(request)  # Log the user out
        return redirect("home")  # Redirect to the home page

shop_proj/users/templates/users/login.html
<!-- TailwindCSS CDN -->
<script src="https://cdn.tailwindcss.com"></script>
<!-- TailwindCSS CDN -->
{% block content %}
  <div class="flex flex-col justify-center items-center min-h-screen bg-gray-50">
    <span class="flex items-center font-bold text-3xl text-gray-800 mb-8">
      <img class="h-10 mr-3" src="https://cdn2.iconfinder.com/data/icons/vivid/48/cart-512.png" alt="ShopFusion Logo" />
      ShopFusion
    </span>

    <form class="bg-white shadow-lg rounded-lg p-8 w-full sm:w-96" method="post">
      {% csrf_token %}
      <div class="text-3xl font-semibold text-gray-700 mb-6">Sign In</div>

      <!-- Username Field -->
      <div class="mb-5">
        <label class="font-semibold text-lg text-gray-600" for="id_username">Username</label>
        <input class="w-full border border-gray-300 rounded-lg px-4 py-2 mt-2 focus:outline-none focus:ring-2 focus:ring-blue-500" type="text" name="username" id="id_username" value="{{ form.username.value|default_if_none:'' }}" placeholder="Enter Your Username" required />
      </div>

      <!-- Password Field -->
      <div class="mb-5">
        <label class="font-semibold text-lg text-gray-600" for="id_password">Password</label>
        <input class="w-full border border-gray-300 rounded-lg px-4 py-2 mt-2 focus:outline-none focus:ring-2 focus:ring-blue-500" type="password" name="password" id="id_password" value="{{ form.password.value|default_if_none:'' }}" placeholder="Enter Your Password" required />
      </div>

      <!-- Login Button -->
      <button class="w-full py-3 bg-blue-500 hover:bg-blue-600 text-white font-semibold rounded-lg transition duration-300 focus:outline-none focus:ring-2 focus:ring-blue-500" type="submit">Sign In</button>

      <!-- Sign Up Redirect -->
      <div class="mt-4 text-center">
        <p class="text-gray-600">
          Don't have an account?
          <a class="text-blue-600 font-semibold" href="{% url 'register' %}">Sign up</a>
        </p>
      </div>
    </form>
  </div>
{% endblock %}

shop_proj/users/templates/users/logout.html
<!-- TailwindCSS CDN -->
<script src="https://cdn.tailwindcss.com"></script>
<!-- TailwindCSS CDN -->

{% block content %}
  <div class="flex flex-col justify-center items-center min-h-screen bg-gray-50">
    <span class="flex items-center font-bold text-3xl text-gray-800 mb-8">
      <img class="h-10 mr-3" src="https://cdn2.iconfinder.com/data/icons/vivid/48/cart-512.png" alt="ShopFusion Logo" />
      ShopFusion
    </span>

    <div class="bg-white shadow-lg rounded-lg p-8 w-full sm:w-96">
      <div class="text-3xl font-semibold text-gray-700 mb-6">Logout Confirmation</div>

      <p class="text-lg text-gray-600 mb-6">Are you sure you want to logout? You will be redirected to the login page.</p>

      <!-- Logout Button -->
      <form method="post" action="{% url 'logout' %}" class="mb-4">
        {% csrf_token %}
        <button type="submit" class="w-full py-3 bg-red-600 hover:bg-red-700 text-white font-semibold rounded-lg transition duration-300 focus:outline-none focus:ring-2 focus:ring-red-500">Logout</button>
      </form>

      <!-- Cancel Button -->
      <div>
        <a href="{% url 'profile' %}" class="block w-full py-3 mb-4 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-lg text-center transition duration-300">Cancel</a>
      </div>
    </div>
  </div>
{% endblock %}

shop_proj/users/templates/users/profile.html
{% extends 'shop_app/baseTemp.html' %}
{% load static %}

{% block title %}
  Profile
{% endblock %}

{% block content %}
  <div class="container mx-auto p-10">
    <!-- Username -->
    <h1 class="text-5xl font-bold text-center text-white mb-6">{{ request.user.username }}</h1>

    <!-- Profile Image -->
    <div class="flex justify-center mb-10">
      <img src="media/media/user_uploads/default-pfp.jpg" alt="Profile Picture" class="h-40 w-40 rounded-full border-4 border-blue-500 shadow-lg" />
    </div>

    <!-- User Information -->
    <div class="bg-gray-400 p-8 rounded-lg shadow-lg">
      <h2 class="text-3xl font-bold text-black mb-4">User Information</h2>
      <div class="flex flex-col space-y-3">
        <div>
          <span class="text-black font-semibold">Username:</span>
          <span class="text-black text-lg font-bold">{{ request.user.username }}</span>
        </div>
        <div>
          <span class="text-black font-semibold">First Name:</span>
          <span class="text-black text-lg font-bold">{{ request.user.first_name }}</span>
        </div>
        <div>
          <span class="text-black font-semibold">Last Name:</span>
          <span class="text-black text-lg font-bold">{{ request.user.last_name }}</span>
        </div>
        <div>
          <span class="text-black font-semibold">Email:</span>
          <span class="text-black text-lg font-bold">{{ request.user.email }}</span>
        </div>
        <div>
          <span class="text-black font-semibold">Joined:</span>
          <span class="text-black text-lg font-bold">{{ request.user.date_joined|date:'F j, Y' }}</span>
        </div>
      </div>
    </div>

    <!-- Actions Section -->
    <div class="mt-8 text-center">
      <h2 class="text-3xl font-bold text-white mb-4">Manage Your Account</h2>
      <div class="flex justify-center space-x-4">
        <a href="#" class="bg-blue-600 hover:bg-blue-700 text-white py-2 px-4 rounded-lg text-lg font-semibold transition duration-200">Edit Profile</a>
        <a href="{% url 'logout' %}" class="bg-red-600 hover:bg-red-700 text-white py-2 px-4 rounded-lg text-lg font-bold transition duration-200">Logout</a>
      </div>
    </div>
  </div>
{% endblock %}

shop_proj/users/templates/users/register.html
<!-- TailwindCSS CDN -->
<script src="https://cdn.tailwindcss.com"></script>
<!-- TailwindCSS CDN -->

{% block content %}
  <div class="flex flex-col justify-center items-center min-h-screen bg-gray-50">
    <span class="flex font-bold text-xl text-gray-800">
      ShopFusion
      <img class="h-9 mx-3" src="https://cdn2.iconfinder.com/data/icons/vivid/48/cart-512.png" alt="ShopFusion Logo" />
    </span>

    <form class="bg-white shadow-2xl p-10 rounded-lg w-auto" method="post">
      {% csrf_token %}
      <div class="text-4xl font-semibold flex justify-start text-gray-500 mb-6 text-center">Create Account</div>

      <!-- First Name -->
      <div class="mb-5">
        <label class="font-semibold text-lg text-gray-600" for="id_first_name">First Name</label>
        <input class="w-full border border-gray-300 rounded-lg px-4 py-2 mt-2 focus:outline-none focus:ring-2 focus:ring-blue-500" type="text" name="first_name" id="id_first_name" value="{{ user_form.first_name.value|default_if_none:'' }}" placeholder="Enter Your First Name" />
      </div>

      <!-- Last Name -->
      <div class="mb-5">
        <label class="font-semibold text-lg text-gray-600" for="id_last_name">Last Name</label>
        <input class="w-full border border-gray-300 rounded-lg px-4 py-2 mt-2 focus:outline-none focus:ring-2 focus:ring-blue-500" type="text" name="last_name" id="id_last_name" value="{{ user_form.last_name.value|default_if_none:'' }}" placeholder="Enter Your Last Name" />
      </div>

      <!-- Username -->
      <div class="mb-5">
        <label class="font-semibold text-lg text-gray-600" for="id_username">Username</label>
        <input class="w-full border border-gray-300 rounded-lg px-4 py-2 mt-2 focus:outline-none focus:ring-2 focus:ring-blue-500" type="text" name="username" id="id_username" value="{{ user_form.username.value|default_if_none:'' }}" placeholder="Enter Your Username" />
      </div>

      <!-- Email -->
      <div class="mb-5">
        <label class="font-semibold text-lg text-gray-600" for="id_email">Email</label>
        <input class="w-full border border-gray-300 rounded-lg px-4 py-2 mt-2 focus:outline-none focus:ring-2 focus:ring-blue-500" type="email" name="email" id="id_email" value="{{ user_form.email.value|default_if_none:'' }}" placeholder="Enter Your Email" />
      </div>

      <!-- Password -->
      <div class="mb-5">
        <label class="font-semibold text-lg text-gray-600" for="id_password">Password</label>
        <input class="w-full border border-gray-300 rounded-lg px-4 py-2 mt-2 focus:outline-none focus:ring-2 focus:ring-blue-500" type="password" name="password" id="id_password" value="{{ user_form.password.value|default_if_none:'' }}" placeholder="Enter Your Password" />
      </div>

      <!-- Confirm Password -->
      <div class="mb-5">
        <label class="font-semibold text-lg text-gray-600" for="id_password2">Confirm Password</label>
        <input class="w-full border border-gray-300 rounded-lg px-4 py-2 mt-2 focus:outline-none focus:ring-2 focus:ring-blue-500" type="password" name="password2" id="id_password2" value="{{ user_form.password2.value|default_if_none:'' }}" placeholder="Confirm Your Password" />
      </div>

      <!-- Sign Up Button -->
      <button class="w-full py-3 bg-blue-500 hover:bg-blue-700 text-white font-semibold rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 transition duration-200" type="submit">Sign up</button>

      <!-- Login Redirect -->
      <div class="mt-4 text-center">
        <p class="text-gray-600">
          Already have an account?
          <a class="text-blue-700 font-semibold" href="{% url 'login' %}">Login Here</a>
        </p>
      </div>
    </form>
  </div>
{% endblock %}