shop_proj/shop_app/urls.py
from django.contrib import admin
from django.urls import path
from shop_app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.home, name="home"),
    path("detail/<int:id>", views.detail, name="detail"),
    path("checkout/", views.checkout, name="checkout"),
    path("seller/", views.seller, name="seller"),
    path("createproduct/", views.create_product, name="createproduct"),
    path("edit/<int:id>", views.product_edit, name="edit"),
    path("delete/<int:id>", views.product_delete, name="delete"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("sales/", views.sales, name="sales"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_proj/shop_proj/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("shop_app.urls")),
    path("user/", include("users.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_proj/users/urls.py
from django.contrib import admin
from django.urls import path
from users import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("register", views.register, name="register"),
    path("login", views.user_login, name="login"),
    path("profile", views.user_profile, name="profile"),
    path(
        "logout",
        views.CustomLogoutView.as_view(
            http_method_names=["post", "get", "option"],
        ),
        name="logout",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_proj/shop_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings


# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=200, default="untitled")
    description = models.TextField()
    price = models.FloatField()
    category = models.CharField(max_length=200, blank=True)
    image = models.ImageField(upload_to="uploads/", default="default.png")
    seller = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="products",
        null=True,
        blank=True,
    )
    total_sales_amount = models.IntegerField(default=0)
    total_sales = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Order(models.Model):
    items = models.CharField(max_length=1000)
    name = models.CharField(max_length=1000)
    email = models.CharField(max_length=1000)
    address = models.CharField(max_length=1000)
    city = models.CharField(max_length=1000)
    state = models.CharField(max_length=1000)
    zipcode = models.CharField(max_length=1000)
    total = models.CharField(max_length=1000)

    def __str__(self):
        return f"{self.name} - ₹ {self.total}"


class OrderDetail(models.Model):
    customer_email = models.EmailField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    amount = models.IntegerField()
    stripe_payment_intent = models.CharField(max_length=200)
    has_paid = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now_add=True)


class Cart(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Cart for {self.user.username}"


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, related_name="items", on_delete=models.CASCADE)
    product = models.ForeignKey("Product", on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} x {self.product.name} in cart"

shop_proj/shop_app/forms.py
from django import forms
from .models import Product
from django.contrib.auth.models import User


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["name", "description", "price", "image"]

shop_proj/shop_app/views.py
from django.shortcuts import redirect, render
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
import datetime


# Create your views here.
def home(request):
    products = Product.objects.all()
    return render(request, "shop_app/home.html", {"products": products})


def detail(request, id):
    details = Product.objects.get(id=id)
    return render(request, "shop_app/detail.html", {"details": details})


def checkout(request):
    if request.method == "POST":
        items = request.POST.get("items", "")
        name = request.POST.get("name", "")
        email = request.POST.get("email", "")
        address = request.POST.get("address", "")
        city = request.POST.get("city", "")
        state = request.POST.get("state", "")
        zipcode = request.POST.get("zipcode", "")
        total = request.POST.get("total", "")

        order = Order(
            items=items,
            name=name,
            email=email,
            address=address,
            city=city,
            state=state,
            zipcode=zipcode,
            total=total,
        )
        order.save()

    return render(
        request,
        "shop_app/checkout.html",
    )


def delete_item(request, id):
    product_objects = Product.objects.get(id=id)
    if request.method == "POST":
        product_objects.delete()
        return redirect("checkout")
    return render(request, "shop/delete.html", {"product_objects": product_objects})


def seller(request):
    products = Product.objects.filter(seller=request.user)
    return render(request, "shop_app/seller.html", {"products": products})


def create_product(request):
    if not request.user.is_authenticated:
        return redirect("login")

    if request.method == "POST":
        product_form = ProductForm(request.POST, request.FILES)
        if product_form.is_valid():
            new_product = product_form.save(commit=False)
            new_product.seller = request.user
            new_product.save()
            return redirect("home")

    product_form = ProductForm()
    return render(
        request, "shop_app/create_product.html", {"product_form": product_form}
    )


def product_edit(request, id):
    product = Product.objects.get(id=id)
    if product.seller != request.user:
        return redirect("invalid")

    product_form = ProductForm(
        request.POST or None, request.FILES or None, instance=product
    )
    if request.method == "POST":
        if product_form.is_valid():
            product_form.save()
            return redirect("home")
    return render(
        request,
        "shop_app/edit.html",
        {"product_form": product_form, "product": product},
    )


def product_delete(request, id):
    product = Product.objects.get(id=id)
    if product.seller != request.user:
        return redirect("invalid")
    if request.method == "POST":
        product.delete()
        return redirect("home")
    return render(request, "shop_app/delete.html", {"product": product})


@login_required
def dashboard(request):
    products = Product.objects.filter(seller=request.user)
    print(products)
    return render(request, "shop_app/dashboard.html", {"products": products})


def sales(request):
    orders = OrderDetail.objects.filter(product__seller=request.user)
    total_sales = orders.aggregate(Sum("amount"))
    print(total_sales)

    # 365 day sales sum
    last_year = datetime.date.today() - datetime.timedelta(days=365)
    data = OrderDetail.objects.filter(
        product__seller=request.user, created_on__gt=last_year
    )
    yearly_sales = data.aggregate(Sum("amount"))

    # 30 day sales sum
    last_month = datetime.date.today() - datetime.timedelta(days=30)
    data = OrderDetail.objects.filter(
        product__seller=request.user, created_on__gt=last_month
    )
    monthly_sales = data.aggregate(Sum("amount"))

    # 7 day sales sum
    last_week = datetime.date.today() - datetime.timedelta(days=7)
    data = OrderDetail.objects.filter(
        product__seller=request.user, created_on__gt=last_week
    )
    weekly_sales = data.aggregate(Sum("amount"))

    # Everday sum for the past 30 days
    daily_sales_sums = (
        OrderDetail.objects.filter(product__seller=request.user)
        .values("created_on__date")
        .order_by("created_on__date")
        .annotate(sum=Sum("amount"))
    )

    product_sales_sums = (
        OrderDetail.objects.filter(product__seller=request.user)
        .values("product__name")
        .order_by("product__name")
        .annotate(sum=Sum("amount"))
    )
    print(product_sales_sums)

    return render(
        request,
        "shop_app/sales.html",
        {
            "total_sales": total_sales,
            "yearly_sales": yearly_sales,
            "monthly_sales": monthly_sales,
            "weekly_sales": weekly_sales,
            "daily_sales_sums": daily_sales_sums,
            "product_sales_sums": product_sales_sums,
        },
    )

shop_proj/shop_app/templates/shop_app/baseTemp.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Tailwind Link -->
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'shop_app/style/output.css' %}" />
    <!-- Tailwind Link -->
    <title>
      {% block title %}
        ShopFusion
      {% endblock %}
    </title>
  </head>
  <body class="bg-white text-black">
    <!-- Navbar -->
    <nav class="bg-white shadow-md">
      <div class="max-w-screen-3xl flex justify-between items-center py-4 px-6">
        <!-- Logo and Tagline -->
        <a class="flex items-center space-x-3 ml-20" href="{% url 'home' %}">
          <img class="h-10" src="{% static 'shop_app/images/logo.png' %}" alt="ShopFusion Logo" />
          <div class="flex flex-col">
            <span class="text-2xl font-bold text-black">ShopFusion</span>
            <span class="text-sm text-black">Shop Smart, Shop Fusion</span>
          </div>
        </a>

        <!-- Navbar Links and User Info -->
        <div class="flex items-center space-x-6 mr-10">
          <!-- Cart Link -->
          <a href="{% url 'checkout' %}" class="flex font-bold items-center text-xl text-black hover:text-gray-700">
            <img class="h-8" src="{% static 'shop_app/images/cart.png' %}" alt="Cart" />
            <span id="cart" class="ml-2">Cart (0)</span>
          </a>

          <!-- Become a Seller Link -->
          <a href="{% url 'seller' %}" class="text-xl font-bold text-black hover:text-gray-700">Become a Seller</a>

          <!-- User Profile or Login -->
          <div class="flex items-center font-bold space-x-4">
            {% if request.user.is_authenticated %}
              <a href="{% url 'profile' %}" class="flex items-center text-xl text-black hover:text-gray-700">
                <img class="h-10 w-10 rounded-full" src="{% static 'shop_app/images/default-pfp.jpg' %}" alt="Profile Picture" />
                <span class="ml-2">{{ request.user.username }}</span>
              </a>
            {% else %}
              <a href="{% url 'login' %}" class="text-xl font-bold text-black hover:text-gray-700">Login</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>

    <!-- Content Block -->
    <div class="container mx-auto py-8">
      {% block content %}

      {% endblock %}
    </div>

    <!-- JavaScript to Handle Cart Functionality -->
    <script type="text/javascript">
      document.addEventListener('DOMContentLoaded', function () {
        // Initialize the cart from localStorage
        let cart = JSON.parse(localStorage.getItem('cart')) || {}
      
        // Function to update Cart Display
        function updateCartDisplay() {
          const cartCount = Object.keys(cart).length // Get the number of items in the cart
          document.getElementById('cart').innerHTML = 'Cart (' + cartCount + ')' // Update cart display
        }
      
        // Initialize Cart Display on page load
        updateCartDisplay()
      
        // Event listener for "Add to Cart" buttons
        document.querySelectorAll('.add-to-cart').forEach(function (button) {
          button.addEventListener('click', function () {
            let itemId = this.id.toString() // Get the ID of the clicked product
      
            // Get product price and name
            const price = parseFloat(document.getElementById('price' + itemId).textContent.replace(/[^\d.-]/g, ''))
            const name = document.getElementById('nm' + itemId).textContent
      
            // Update cart quantity and price
            if (cart[itemId] != undefined) {
              const quantity = cart[itemId][0] + 1 // Increment quantity
              cart[itemId][0] = quantity // Update quantity
              cart[itemId][2] = cart[itemId][2] + price // Update total price
            } else {
              cart[itemId] = [1, name, price] // Add new product to cart
            }
      
            // Log updated cart to console for debugging
            console.log(cart)
      
            // Save updated cart to localStorage
            localStorage.setItem('cart', JSON.stringify(cart))
      
            // Update Cart Display after adding an item
            updateCartDisplay()
          })
        })
      })
    </script>
  </body>
</html>

shop_proj/shop_app/templates/shop_app/checkout.html
{% extends 'shop_app/baseTemp.html' %}
{% load static %}
{% block title %}
  CheckOut
{% endblock %}
{% block content %}
  <div class="container mx-auto px-4 py-8">
    <!-- Shopping Cart Section -->
    <div class="w-full">
      <ul class="bg-white shadow-md rounded-lg p-6 mb-8" id="item_list">
        <h1 class="text-3xl font-semibold text-black mb-4">Shopping Cart</h1>
        <br />
      </ul>
      <!-- Clear Cart Button -->
      <div class="flex justify-end">
        <button type="button" id="clearCart" class="w-auto py-3 px-6 bg-red-600 text-white font-semibold rounded-lg hover:bg-red-700 transition duration-200">Clear Cart</button>
      </div>
    </div>

    <!-- Order Details Form -->
    <div class="w-full">
      <form method="POST" class="bg-white shadow-md rounded-lg p-6 space-y-6">
        {% csrf_token %}
        <h1 class="text-3xl font-semibold text-black">Order Details</h1>
        <input type="hidden" id="items" name="items" />

        <!-- Name Field -->
        <div>
          <label for="name" class="block text-lg font-medium text-black">Name</label>
          <input id="name" name="name" type="text" placeholder="John" class="mt-1 block border-2 w-1/2 p-3 rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-200 focus:ring-opacity-50" />
        </div>

        <!-- Email Field -->
        <div>
          <label for="email" class="block text-lg font-medium text-black">Email</label>
          <input id="email" name="email" type="email" placeholder="john@gmail.com" class="mt-1 border-2 block w-1/2 rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring p-3 focus:ring-blue-200 focus:ring-opacity-50" />
        </div>

        <!-- Address Field -->
        <div>
          <label for="address" class="block text-lg font-medium text-black">Address</label>
          <input id="address" name="address" type="text" placeholder="1234 Main St" class="mt-1 border-2 block w-1/2 rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring p-3 focus:ring-blue-200 focus:ring-opacity-50" />
        </div>

        <!-- City Field -->
        <div>
          <label for="city" class="block text-lg font-medium text-black">City</label>
          <input id="city" name="city" type="text" class="mt-1 border-2 block w-1/2 rounded-md border-gray-300 p-3 shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-200 focus:ring-opacity-50" />
        </div>

        <!-- State Field -->
        <div>
          <label for="state" class="block text-lg font-medium text-black">State</label>
          <input id="state" name="state" type="text" class="mt-1 border-2 block w-1/2 rounded-md border-gray-300 p-3 shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-200 focus:ring-opacity-50" />
        </div>

        <!-- Zip Code Field -->
        <div>
          <label for="zipcode" class="block text-lg font-medium text-black">Zip</label>
          <input id="zipcode" name="zipcode" type="text" class="mt-1 border-2 block w-1/2 rounded-md border-gray-300 p-3 shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-200 focus:ring-opacity-50" />
        </div>

        <!-- Amount to be Paid Field -->
        <div>
          <label for="total" class="block text-lg font-medium text-black">Amount to be paid</label>
          <input readonly type="text" id="total" name="total" class="mt-1 border-2 block w-1/2 rounded-md border-gray-300 p-3 bg-gray-100 shadow-sm" />
        </div>

        <!-- Submit Button -->
        <div class="flex justify-start">
          <button type="submit" class="w-auto py-3 px-6 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition duration-200">Place Order</button>
        </div>
      </form>

      <!-- Continue Shopping -->
      <div class="mt-6 flex justify-center">
        <a class="block text-center w-full text-xl rounded-full px-6 py-3 bg-yellow-600 hover:bg-yellow-700 text-white font-bold" href="{% url 'home' %}">Continue Shopping</a>
      </div>
    </div>

    <script type="text/javascript">
      let cart = localStorage.getItem('cart') ? JSON.parse(localStorage.getItem('cart')) : {}
      let total = 0
      let totalQuantity = 0
      
      for (let item in cart) {
        let name = cart[item][1]
        let quantity = cart[item][0]
        let price = cart[item][2]
        total += price * quantity
        totalQuantity += quantity
      
        let itemString = `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <li class="flex justify-between items-center py-3 border-b border-gray-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h5 class="text-lg font-semibold text-black">${name}</h5>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span class="text-gray-600">Quantity: ${quantity}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span class="text-lg font-semibold text-yellow-500">₹ ${price.toLocaleString('en-US')}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </li>`
        document.getElementById('item_list').insertAdjacentHTML('beforeend', itemString)
      }
      
      let formattedTotal = total.toLocaleString('en-US')
      let totalPrice = `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <li class="flex justify-between items-center py-3 mt-4 border-t border-gray-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3 class="text-2xl font-bold text-black">Subtotal (${totalQuantity} items)</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span class="text-2xl font-bold text-green-600">₹ ${formattedTotal}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </li>`
      
      document.getElementById('total').value = formattedTotal
      document.getElementById('item_list').insertAdjacentHTML('beforeend', totalPrice)
      document.getElementById('items').value = JSON.stringify(cart)
      
      // Clear Cart functionality
      document.getElementById('clearCart').addEventListener('click', function () {
        localStorage.removeItem('cart') // Removes the cart from localStorage
        document.getElementById('item_list').innerHTML = '' // Clears the cart display
        document.getElementById('total').value = '₹ 0' // Resets the total
        window.location.href = "{% url 'checkout' %}"
      })
    </script>
  </div>
{% endblock %}

shop_proj/shop_app/templates/shop_app/create_product.html
{% extends 'shop_app/baseTemp.html' %}
{% block title %}
  Add New Product
{% endblock %}

{% block content %}
  <div class="flex justify-center items-center min-h-screen bg-gray-50">
    <div class="w-full max-w-lg bg-white shadow-lg rounded-lg p-8 m-4 border border-gray-200">
      <h2 class="text-3xl font-semibold text-gray-800 text-center mb-8">Add New Product</h2>

      <form method="POST" enctype="multipart/form-data" class="space-y-6">
        {% csrf_token %}

        <!-- Product Name -->
        <div>
          <label for="name" class="block text-gray-700 font-medium mb-2">Product Name</label>
          <input type="text" id="id_name" name="name" value="{{ product_form.name.value|default_if_none:'' }}" class="w-full border border-gray-300 rounded-lg p-4 focus:ring-2 focus:ring-blue-500 focus:outline-none" placeholder="Enter product name" />
        </div>

        <!-- Product Description -->
        <div>
          <label for="description" class="block text-gray-700 font-medium mb-2">Description</label>
          <input type="text" id="id_description" name="description" value="{{ product_form.description.value|default_if_none:'' }}" class="w-full border border-gray-300 rounded-lg p-4 focus:ring-2 focus:ring-blue-500 focus:outline-none" placeholder="Enter product description" />
        </div>

        <!-- Product Price -->
        <div>
          <label for="price" class="block text-gray-700 font-medium mb-2">Price</label>
          <input type="number" id="id_price" name="price" value="{{ product_form.price.value|default_if_none:'' }}" class="w-full border border-gray-300 rounded-lg p-4 focus:ring-2 focus:ring-blue-500 focus:outline-none" placeholder="Enter product price" />
        </div>

        <!-- Product Image -->
        <div>
          <label for="image" class="block text-gray-700 font-medium mb-2">Product Image</label>
          <input type="file" id="id_image" name="image" class="w-full border border-gray-300 rounded-lg p-4 bg-gray-50 focus:ring-2 focus:ring-blue-500 focus:outline-none" />
        </div>

        <!-- Submit Button -->
        <button type="submit" class="w-full bg-blue-600 text-white font-semibold py-4 rounded-lg hover:bg-blue-700 transition duration-300">Add Product</button>
      </form>
    </div>
  </div>
{% endblock %}

shop_proj/shop_app/templates/shop_app/edit.html
{% extends 'shop_app/baseTemp.html' %}
{% load static %}

{% block title %}
  Edit Product
{% endblock %}

{% block content %}
  <div class="flex flex-col justify-center items-center min-h-screen bg-gray-100">
    <div class="w-full max-w-lg bg-white shadow-lg rounded-lg p-8 m-4">
      <h2 class="text-3xl font-semibold text-gray-800 text-center mb-8">Edit Product</h2>

      <form method="POST" enctype="multipart/form-data" class="space-y-6">
        {% csrf_token %}

        <div>
          <label for="name" class="block text-gray-600 font-medium mb-2">Name</label>
          <input type="text" id="id_name" name="name" value="{{ product_form.name.value|default_if_none:'' }}" class="w-full border border-gray-300 rounded-lg p-3 focus:ring-2 focus:ring-blue-400 focus:outline-none" placeholder="Enter product name" />
        </div>

        <div>
          <label for="description" class="block text-gray-600 font-medium mb-2">Description</label>
          <input type="text" id="id_description" name="description" value="{{ product_form.description.value|default_if_none:'' }}" class="w-full border border-gray-300 rounded-lg p-3 focus:ring-2 focus:ring-blue-400 focus:outline-none" placeholder="Enter description of product" />
        </div>

        <div>
          <label for="price" class="block text-gray-600 font-medium mb-2">Price</label>
          <input type="number" id="id_price" name="price" value="{{ product_form.price.value|default_if_none:'' }}" class="w-full border border-gray-300 rounded-lg p-3 focus:ring-2 focus:ring-blue-400 focus:outline-none" placeholder="Enter price of product" />
        </div>

        <div>
          <label for="image" class="block text-gray-600 font-medium mb-2">Product Image</label>
          <div class="w-full border border-gray-300 rounded-lg p-3 bg-gray-50 focus:outline-none">{{ product_form.image }}</div>
        </div>

        <!-- Action Buttons -->
        <div class="flex space-x-4">
          <!-- Update Button -->
          <button type="submit" class="w-1/2 bg-blue-500 text-white font-semibold py-3 rounded-full hover:bg-blue-700 transition duration-200">Update</button>

          <!-- Delete Button -->
          <a href="{% url 'delete' product.id %}" class="inline-block w-1/2 bg-red-500 text-white font-semibold py-3 rounded-full text-center hover:bg-red-700 transition duration-200">Delete</a>
        </div>

        <!-- Home Button -->
        <div class="mt-6">
          <a href="{% url 'home' %}" class="inline-block w-full bg-green-500 text-white font-semibold py-3 rounded-full text-center hover:bg-green-700 transition duration-200">Home</a>
        </div>
      </form>
    </div>
  </div>
{% endblock %}